/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef CONSTABLE_H
#define CONSTABLE_H

/* function declarations */
void init_consTable(void);
void initialize_table_consTable(void);
Netsnmp_Node_Handler consTable_handler;
Netsnmp_First_Data_Point  consTable_get_first_data_point;
Netsnmp_Next_Data_Point   consTable_get_next_data_point;

/* column number definitions for table consTable */
       #define COLUMN_INDEXCONS		1
       #define COLUMN_CONSROWSTATUS		2
       #define COLUMN_CONSDATA1		3
       #define COLUMN_CONSDATA2		4
       #define COLUMN_CONSDATA3		5
       #define COLUMN_CONSDATA4		6
       #define COLUMN_CONSDATA5		7
       #define COLUMN_CONSDATA6		8
       #define COLUMN_CONSDATA7		9
       #define COLUMN_CONSDATA8		10
#endif /* CONSTABLE_H */
