/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "consTable.h"
#include "LoopApp.h"



/** Initializes the consTable module */
struct consTable_entry *
consTable_createEntry(
                 long  indexcons
                );
                    
void
init_consTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_consTable();
}


/** Initialize the consTable table by defining its contents and how it's structured */
void
initialize_table_consTable(void)
{
    const oid consTable_oid[] = {1,3,6,1,4,1,71200,3};
    const size_t consTable_oid_len   = OID_LENGTH(consTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("consTable:init", "initializing table consTable\n"));

    reg = netsnmp_create_handler_registration(
              "consTable",     consTable_handler,
              consTable_oid, consTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: indexcons */
                           0);
    table_info->min_column = COLUMN_CONSROWSTATUS;
    table_info->max_column = COLUMN_CONSDATA8;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = consTable_get_first_data_point;
    iinfo->get_next_data_point  = consTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    int i = 0;
    for(i=1;i<5;i++)    consTable_createEntry(i);
}

    /* Typical data structure for a row entry */
struct consTable_entry {
    /* Index values */
    long indexcons;

    /* Column values */
    long consrowstatus;
    char consdata1[CONST_LEN];
    size_t consdata1_len;
    char consdata2[CONST_LEN];
    size_t consdata2_len;
    char consdata3[CONST_LEN];
    size_t consdata3_len;
    char consdata4[CONST_LEN];
    size_t consdata4_len;
    char consdata5[CONST_LEN];
    size_t consdata5_len;
    char consdata6[CONST_LEN];
    size_t consdata6_len;
    char consdata7[CONST_LEN];
    size_t consdata7_len;
    char consdata8[CONST_LEN];
    size_t consdata8_len;

    /* Illustrate using a simple linked list */
    int   valid;
    struct consTable_entry *next;
};

struct consTable_entry  *consTable_head;

/* create a new row in the (unsorted) table */
struct consTable_entry *
consTable_createEntry(
                 long  indexcons
                ) {
    struct consTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct consTable_entry);
    if (!entry)
        return NULL;
    memset(entry,0,sizeof(struct consTable_entry));
    entry->indexcons = indexcons;
    entry->next = consTable_head;
    consTable_head = entry;
    entry->consdata1_len = CONST_LEN;
    entry->consdata2_len = CONST_LEN;
    entry->consdata3_len = CONST_LEN;
    entry->consdata4_len = CONST_LEN;
    entry->consdata5_len = CONST_LEN;
    entry->consdata6_len = CONST_LEN;
    entry->consdata7_len = CONST_LEN;
    entry->consdata8_len = CONST_LEN;
    return entry;
}

/* remove a row from the table */
void
consTable_removeEntry( struct consTable_entry *entry ) {
    struct consTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = consTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        consTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
consTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = consTable_head;
    return consTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
consTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct consTable_entry *entry = (struct consTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->indexcons );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the consTable table */
int
consTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct consTable_entry          *table_entry;

    DEBUGMSGTL(("consTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct consTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONSROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->consrowstatus);
                break;
            case COLUMN_CONSDATA1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata1,dev->vi[0],CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata1, dev->vq[0], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata1, &dev->vi[0][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata1, &dev->vq[0][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata1,"Consindex1 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata1,
                                          table_entry->consdata1_len);
                break;
            case COLUMN_CONSDATA2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata2,dev->vi[1],CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata2,dev->vq[1],CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata2, &dev->vi[1][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata2, &dev->vq[1][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata2,"Consindex2 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata2,
                                          table_entry->consdata2_len);
                break;
            case COLUMN_CONSDATA3:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata3, dev->vi[2], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata3, dev->vq[2], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata3, &dev->vi[2][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata3, &dev->vq[2][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata3,"Consindex3 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata3,
                                          table_entry->consdata3_len);
                break;
            case COLUMN_CONSDATA4:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata4, dev->vi[3], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata4, dev->vq[3], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata4, &dev->vi[3][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata4, &dev->vq[3][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata4,"Consindex4 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata4,
                                          table_entry->consdata4_len);
                break;
            case COLUMN_CONSDATA5:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata5, dev->vi[4], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata5, dev->vq[4], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata5, &dev->vi[4][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata5, &dev->vq[4][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata5,"Consindex5 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata5,
                                          table_entry->consdata5_len);
                break;
            case COLUMN_CONSDATA6:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata6, dev->vi[5], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata6, dev->vq[5], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata6, &dev->vi[5][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata6, &dev->vq[5][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata6,"Consindex6 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata6,
                                          table_entry->consdata6_len);
                break;
            case COLUMN_CONSDATA7:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata7, dev->vi[6], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata7, dev->vq[6], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata7, &dev->vi[6][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata7, &dev->vq[6][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata7,"Consindex7 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata7,
                                          table_entry->consdata7_len);
                break;
            case COLUMN_CONSDATA8:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                switch(table_entry->indexcons){
                    case 1:
                        memcpy(table_entry->consdata8, dev->vi[7], CONST_LEN);
                        break;
                    case 2:
                        memcpy(table_entry->consdata8, dev->vq[7], CONST_LEN);
                        break;
                    case 3:
                        memcpy(table_entry->consdata8, &dev->vi[7][CONST_LEN], CONST_LEN);
                        break;
                    case 4:
                        memcpy(table_entry->consdata8, &dev->vq[7][CONST_LEN], CONST_LEN);
                        break;
                    default:
                        strcpy(table_entry->consdata8,"Consindex8 error, Pls check!");
                }
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->consdata8,
                                          table_entry->consdata8_len);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct consTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_CONSROWSTATUS:
                // ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         // (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // default:
                // netsnmp_set_request_error( reqinfo, request,
                                           // SNMP_ERR_NOTWRITABLE );
                // return SNMP_ERR_NOERROR;
            // }
        // }
        break;

    case MODE_SET_RESERVE2:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct consTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_CONSROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // table_row = consTable_createEntry(
                        // , *table_info->indexes->val.integer
                        // );
                    // if (table_row) {
                        // netsnmp_insert_iterator_context( request, table_row );
                    // } else {
                        // netsnmp_set_request_error( reqinfo, request,
                                                   // SNMP_ERR_RESOURCEUNAVAILABLE );
                        // return SNMP_ERR_NOERROR;
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_FREE:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct consTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_CONSROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // consTable_removeEntry(table_data, table_row );
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct consTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct consTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_CONSROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (/* XXX */0) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct consTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_CONSROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // consTable_removeEntry(table_data, table_row );
                    // }
                // }
                // break;
            // }
        // }
        break;

    case MODE_SET_COMMIT:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct consTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_CONSROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_ACTIVE:
                    // table_entry->consrowstatus = RS_ACTIVE;
                    // break;

                // case RS_CREATEANDWAIT:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_NOTINSERVICE:
                    // table_entry->consrowstatus = RS_NOTINSERVICE;
                    // break;

                // case RS_DESTROY:
                    // consTable_removeEntry(table_data, table_row );
                // }
            // }
        // }
        break;
    }
    return SNMP_ERR_NOERROR;
}
