/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef DEVIP_H
#define DEVIP_H

/* function declarations */
void init_devip(void);
Netsnmp_Node_Handler handle_ipaddr;
Netsnmp_Node_Handler handle_submask;
Netsnmp_Node_Handler handle_gateway;
Netsnmp_Node_Handler handle_apply;
Netsnmp_Node_Handler handle_devmode;
Netsnmp_Node_Handler handle_sysreset;

#endif /* DEVIP_H */
