/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "sateTable.h"
#include "LoopApp.h"
#include "gpio_i2c.h"
#include <stdio.h>
#include <stdlib.h>

#define STRLEN 32

int static_apply[MAX_CHANNEL_NUM] = {0};
/** Initializes the sateTable module */
struct sateTable_entry *
sateTable_createEntry(
                 long  index
                );

void
init_sateTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_sateTable();
}



/** Initialize the sateTable table by defining its contents and how it's structured */
void
initialize_table_sateTable(void)
{
    const oid sateTable_oid[] = {1,3,6,1,4,1,71200,2};
    const size_t sateTable_oid_len   = OID_LENGTH(sateTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("sateTable:init", "initializing table sateTable\n"));

    reg = netsnmp_create_handler_registration(
              "sateTable",     sateTable_handler,
              sateTable_oid, sateTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: index */
                           0);
    table_info->min_column = COLUMN_SATEROWSTATUS;
    table_info->max_column = COLUMN_SATEAPPLY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = sateTable_get_first_data_point;
    iinfo->get_next_data_point  = sateTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    int i = 0;
    for(i=0;i<MAX_CHANNEL_NUM;i++)    sateTable_createEntry(i);
}

    /* Typical data structure for a row entry */
struct sateTable_entry {
    /* Index values */
    long index;

    /* Column values */
    long saterowstatus;
    long inputport;
    long mode;
    long frequency;
    long modulation;
    long symbolrate;
    long fec;
    long spectrum;
    long rolloff;
    long pilot;
    long freqSearchRange;
    char reserve1[32];
    char reserve2[32];
    char reserve3[32];
    char reserve4[32];
    char reserve5[32];
    char reserve6[32];
    char reserve7[32];
    char reserve8[32];
    long reserve1_len;
    long reserve2_len;
    long reserve3_len;
    long reserve4_len;
    long reserve5_len;
    long reserve6_len;
    long reserve7_len;
    long reserve8_len;
    long rxpwr;
    long snr;
    long mer;
    long evm;
    long ebn0;
    long freqoffset;
    long symoffset;
    long agclock;
    long feclock;
    long corrRsErrorsSDSS;
    long rsErrorsSDSS;
    long berWindowSDSS;
    long berCountSDSS;
    long corrRsErrors1SDSS;
    long rsErrors1SDSS;
    long berWindowIter1SDSS;
    long berCountIter1SDSS;
    long crcErrorsS2;
    long packetErrorCountS2;
    long totalPacketsS2;
    long ber;
    char reserve11[32];
    char reserve12[32];
    char reserve13[32];
    long reserve11_len;
    long reserve12_len;
    long reserve13_len;
    long sateapply;


    /* Illustrate using a simple linked list */
    int   valid;
    struct sateTable_entry *next;
};

struct sateTable_entry  *sateTable_head;

/* create a new row in the (unsorted) table */
struct sateTable_entry *
sateTable_createEntry(
                 long  index
                ) {
    struct sateTable_entry *entry;
//    SATDATA_t sd = {0};
    entry = SNMP_MALLOC_TYPEDEF(struct sateTable_entry);
    if (!entry)
        return NULL;
//    memset(entry,0,sizeof(struct sateTable_entry));
    entry->index = index;
    entry->next = sateTable_head;
    sateTable_head = entry;

    entry->reserve1_len = STRLEN;     entry->reserve2_len = STRLEN;
    entry->reserve3_len = STRLEN;     entry->reserve4_len = STRLEN;
    entry->reserve5_len = STRLEN;     entry->reserve6_len = STRLEN;
    entry->reserve7_len = STRLEN;     entry->reserve8_len = STRLEN;
    entry->reserve11_len = STRLEN;    entry->reserve12_len = STRLEN;
    entry->reserve13_len = STRLEN;   
    return entry;
}

/* remove a row from the table */
void
sateTable_removeEntry( struct sateTable_entry *entry ) {
    struct sateTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = sateTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        sateTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
sateTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = sateTable_head;
    return sateTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
sateTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct sateTable_entry *entry = (struct sateTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->index );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the sateTable table */
int
sateTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct sateTable_entry          *table_entry;

    DEBUGMSGTL(("sateTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sateTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SATEROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->saterowstatus);
                break;
            case COLUMN_INPUTPORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->inputport = 1;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->inputport);
                break;
            case COLUMN_MODE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->mode = dev->sdPtr[table_entry->index]->standardMask;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->mode);
                break;
            case COLUMN_FREQUENCY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->frequency = dev->sdPtr[table_entry->index]->frequencyInKHz;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->frequency);
                break;
            case COLUMN_MODULATION:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->modulation = dev->sdPtr[table_entry->index]->modulation;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->modulation);
                break;
            case COLUMN_SYMBOLRATE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->symbolrate = dev->sdPtr[table_entry->index]->symbolRateKSps;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->symbolrate);
                break;
            case COLUMN_FEC:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->fec = dev->sdPtr[table_entry->index]->fecFormat;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->fec);
                break;
            case COLUMN_SPECTRUM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->spectrum = dev->sdPtr[table_entry->index]->spectrumInfo;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->spectrum);
                break;
            case COLUMN_ROLLOFF:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->rolloff = dev->sdPtr[table_entry->index]->rollOff;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rolloff);
                break;
            case COLUMN_PILOT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->pilot = dev->sdPtr[table_entry->index]->pilots;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->pilot);
                break;
            case COLUMN_FREQSEARCHRANGE:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->freqSearchRange = dev->sdPtr[table_entry->index]->freqSearchRangeKHz;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->freqSearchRange);
                break;
            case COLUMN_RESERVE1:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve1,"Reserve1_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve1,
                                          table_entry->reserve1_len);
                break;
            case COLUMN_RESERVE2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve2,"Reserve2_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve2,
                                          table_entry->reserve2_len);
                break;
            case COLUMN_RESERVE3:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve3,"Reserve3_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve3,
                                          table_entry->reserve3_len);
                break;
            case COLUMN_RESERVE4:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve4,"Reserve4_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve4,
                                          table_entry->reserve4_len);
                break;
            case COLUMN_RESERVE5:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve5,"Reserve5_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve5,
                                          table_entry->reserve5_len);
                break;
            case COLUMN_RESERVE6:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve6,"Reserve6_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve6,
                                          table_entry->reserve6_len);
                break;
            case COLUMN_RESERVE7:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve7,"Reserve7_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve7,
                                          table_entry->reserve7_len);
                break;
            case COLUMN_RESERVE8:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve8,"Reserve8_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve8,
                                          table_entry->reserve8_len);
                break;
            case COLUMN_RXPWR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->rxpwr = dev->sdPtr[table_entry->index]->pwr_100dbm;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rxpwr);
                break;
            case COLUMN_SNR:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->snr = dev->sdPtr[table_entry->index]->snr;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->snr);
                break;
            case COLUMN_MER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->mer = dev->sdPtr[table_entry->index]->mer;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->mer);
                break;
            case COLUMN_EVM:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->evm = dev->sdPtr[table_entry->index]->evm;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->evm);
                break;
            case COLUMN_EBN0:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->ebn0 = dev->sdPtr[table_entry->index]->ebn0;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ebn0);
                break;
            case COLUMN_FREQOFFSET:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->freqoffset = dev->sdPtr[table_entry->index]->cfo_Hz;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->freqoffset);
                break;
            case COLUMN_SYMOFFSET:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->symoffset = dev->sdPtr[table_entry->index]->fo_symbol;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->symoffset);
                break;
            case COLUMN_AGCLOCK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->agclock = dev->sdPtr[table_entry->index]->agcLock;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->agclock);
                break;
            case COLUMN_FECLOCK:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->feclock = dev->sdPtr[table_entry->index]->fecLock;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->feclock);
                break;
            case COLUMN_CORRRSERRORSSDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->corrRsErrorsSDSS = dev->sdPtr[table_entry->index]->corrRsErrors;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->corrRsErrorsSDSS);
                break;
            case COLUMN_RSERRORSSDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->rsErrorsSDSS = dev->sdPtr[table_entry->index]->rsErrors;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rsErrorsSDSS);
                break;
            case COLUMN_BERWINDOWSDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->berWindowSDSS = dev->sdPtr[table_entry->index]->berWindow;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->berWindowSDSS);
                break;
            case COLUMN_BERCOUNTSDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->berCountSDSS = dev->sdPtr[table_entry->index]->berCount;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->berCountSDSS);
                break;
            case COLUMN_CORRRSERRORS1SDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->corrRsErrors1SDSS = dev->sdPtr[table_entry->index]->corrRsErrors1;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->corrRsErrors1SDSS);
                break;
            case COLUMN_RSERRORS1SDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->corrRsErrors1SDSS = dev->sdPtr[table_entry->index]->rsErrors1;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rsErrors1SDSS);
                break;
            case COLUMN_BERWINDOWITER1SDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->berWindowIter1SDSS = dev->sdPtr[table_entry->index]->berWindow_Iter1;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->berWindowIter1SDSS);
                break;
            case COLUMN_BERCOUNTITER1SDSS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->berCountIter1SDSS = dev->sdPtr[table_entry->index]->berCount_Iter1;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->berCountIter1SDSS);
                break;
            case COLUMN_CRCERRORSS2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->crcErrorsS2 = dev->sdPtr[table_entry->index]->crcErrors;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->crcErrorsS2);
                break;
            case COLUMN_PACKETERRORCOUNTS2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->packetErrorCountS2 = dev->sdPtr[table_entry->index]->packetErrorCount;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->packetErrorCountS2);
                break;
            case COLUMN_TOTALPACKETSS2:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->totalPacketsS2 = dev->sdPtr[table_entry->index]->totalPackets;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->totalPacketsS2);
                break;
            case COLUMN_BER:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->ber = dev->sdPtr[table_entry->index]->ber_1e_7;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->ber);
                break;
            case COLUMN_RESERVE11:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve11,"Reserve11_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve11,
                                          table_entry->reserve11_len);
                break;
            case COLUMN_RESERVE12:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve12,"Reserve12_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve12,
                                          table_entry->reserve12_len);
                break;
            case COLUMN_RESERVE13:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->reserve13,"Reserve13_empty");
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->reserve13,
                                          table_entry->reserve13_len);
                break;
            case COLUMN_SATEAPPLY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->sateapply = static_apply[table_entry->index];
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->sateapply);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct sateTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATEROWSTATUS:
                // ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         // (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_INPUTPORT:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_MODE:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_FREQUENCY:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_MODULATION:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_SYMBOLRATE:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_FEC:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_SPECTRUM:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_ROLLOFF:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_PILOT:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_FREQSEARCHRANGE:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE1:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve1));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE2:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve2));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE3:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve3));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE4:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve4));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE5:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve5));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE6:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve6));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE7:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve7));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RESERVE8:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->reserve8));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_SATEAPPLY:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // default:
                // netsnmp_set_request_error( reqinfo, request,
                                           // SNMP_ERR_NOTWRITABLE );
                // return SNMP_ERR_NOERROR;
            // }
        // }
        break;

    case MODE_SET_RESERVE2:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct sateTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATEROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // table_row = sateTable_createEntry(
                        // , *table_info->indexes->val.integer
                        // );
                    // if (table_row) {
                        // netsnmp_insert_iterator_context( request, table_row );
                    // } else {
                        // netsnmp_set_request_error( reqinfo, request,
                                                   // SNMP_ERR_RESOURCEUNAVAILABLE );
                        // return SNMP_ERR_NOERROR;
                    // }
                // }
            // }
        // }
        // break;

    // case MODE_SET_FREE:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct sateTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATEROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // sateTable_removeEntry(table_data, table_row );
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct sateTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_INPUTPORT:
                table_entry->inputport     = *request->requestvb->val.integer;
                break;
            case COLUMN_MODE:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->mode     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->standardMask = table_entry->mode; 
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_FREQUENCY:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->frequency     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->frequencyInKHz = table_entry->frequency;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_MODULATION:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->modulation     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->modulation = table_entry->modulation;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_SYMBOLRATE:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->symbolrate     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->symbolRateKSps = table_entry->symbolrate;
                static_apply[table_entry->index] = 1;

                break;
            case COLUMN_FEC:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->fec     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->fecFormat = table_entry->fec;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_SPECTRUM:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->spectrum     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->spectrumInfo = table_entry->spectrum;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_ROLLOFF:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->rolloff     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->rollOff = table_entry->rolloff;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_PILOT:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->pilot     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->pilots = table_entry->pilot;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_FREQSEARCHRANGE:
                dev->sdPtr[table_entry->index]->parachange = 1;
                table_entry->freqSearchRange     = *request->requestvb->val.integer;
                dev->sdPtr[table_entry->index]->freqSearchRangeKHz = table_entry->freqSearchRange;
                static_apply[table_entry->index] = 1;
                break;
            case COLUMN_RESERVE1:
                memset( table_entry->reserve1, 0,
                        sizeof(table_entry->reserve1));
                memcpy( table_entry->reserve1,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve1_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE2:
                memset( table_entry->reserve2, 0,
                        sizeof(table_entry->reserve2));
                memcpy( table_entry->reserve2,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve2_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE3:
                memset( table_entry->reserve3, 0,
                        sizeof(table_entry->reserve3));
                memcpy( table_entry->reserve3,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve3_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE4:
                memset( table_entry->reserve4, 0,
                        sizeof(table_entry->reserve4));
                memcpy( table_entry->reserve4,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve4_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE5:
                memset( table_entry->reserve5, 0,
                        sizeof(table_entry->reserve5));
                memcpy( table_entry->reserve5,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve5_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE6:
                memset( table_entry->reserve6, 0,
                        sizeof(table_entry->reserve6));
                memcpy( table_entry->reserve6,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve6_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE7:
                memset( table_entry->reserve7, 0,
                        sizeof(table_entry->reserve7));
                memcpy( table_entry->reserve7,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve7_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_RESERVE8:
                memset( table_entry->reserve8, 0,
                        sizeof(table_entry->reserve8));
                memcpy( table_entry->reserve8,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->reserve8_len =
                        request->requestvb->val_len;
                break;
            case COLUMN_SATEAPPLY:
                table_entry->sateapply     = *request->requestvb->val.integer;
                if(static_apply[table_entry->index]){
//                    mxl_lockDemod(g_status, 1, table_entry->index/MAX_CHANNEL_NUM,1,
//                    table_entry->index % MAX_CHANNEL_NUM, dev->sdPtr[table_entry->index] );
                    mxl_lockDemodV2(dev, 1, 0, (MXL_HYDRA_DEMOD_ID_E)table_entry->index);
                }
                static_apply[table_entry->index] = 0;
                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct sateTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SATEROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                     if (/* XXX */0) {
                         netsnmp_set_request_error( reqinfo, request,
                                                    SNMP_ERR_INCONSISTENTVALUE );
                         return SNMP_ERR_NOERROR;
                     }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct sateTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATEROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // sateTable_removeEntry(table_data, table_row );
                    // }
                // }
                // break;
            // case COLUMN_INPUTPORT:
                // table_entry->inputport     = table_entry->old_inputport;
                // table_entry->old_inputport = 0;
                // break;
            // case COLUMN_MODE:
                // table_entry->mode     = table_entry->old_mode;
                // table_entry->old_mode = 0;
                // break;
            // case COLUMN_FREQUENCY:
                // table_entry->frequency     = table_entry->old_frequency;
                // table_entry->old_frequency = 0;
                // break;
            // case COLUMN_MODULATION:
                // table_entry->modulation     = table_entry->old_modulation;
                // table_entry->old_modulation = 0;
                // break;
            // case COLUMN_SYMBOLRATE:
                // table_entry->symbolrate     = table_entry->old_symbolrate;
                // table_entry->old_symbolrate = 0;
                // break;
            // case COLUMN_FEC:
                // table_entry->fec     = table_entry->old_fec;
                // table_entry->old_fec = 0;
                // break;
            // case COLUMN_SPECTRUM:
                // table_entry->spectrum     = table_entry->old_spectrum;
                // table_entry->old_spectrum = 0;
                // break;
            // case COLUMN_ROLLOFF:
                // table_entry->rolloff     = table_entry->old_rolloff;
                // table_entry->old_rolloff = 0;
                // break;
            // case COLUMN_PILOT:
                // table_entry->pilot     = table_entry->old_pilot;
                // table_entry->old_pilot = 0;
                // break;
            // case COLUMN_FREQSEARCHRANGE:
                // table_entry->freqSearchRange     = table_entry->old_freqSearchRange;
                // table_entry->old_freqSearchRange = 0;
                // break;
            // case COLUMN_RESERVE1:
                // memcpy( table_entry->reserve1,
                        // table_entry->old_reserve1,
                        // sizeof(table_entry->reserve1));
                // memset( table_entry->old_reserve1, 0,
                        // sizeof(table_entry->reserve1));
                // table_entry->reserve1_len =
                        // table_entry->old_reserve1_len;
                // break;
            // case COLUMN_RESERVE2:
                // memcpy( table_entry->reserve2,
                        // table_entry->old_reserve2,
                        // sizeof(table_entry->reserve2));
                // memset( table_entry->old_reserve2, 0,
                        // sizeof(table_entry->reserve2));
                // table_entry->reserve2_len =
                        // table_entry->old_reserve2_len;
                // break;
            // case COLUMN_RESERVE3:
                // memcpy( table_entry->reserve3,
                        // table_entry->old_reserve3,
                        // sizeof(table_entry->reserve3));
                // memset( table_entry->old_reserve3, 0,
                        // sizeof(table_entry->reserve3));
                // table_entry->reserve3_len =
                        // table_entry->old_reserve3_len;
                // break;
            // case COLUMN_RESERVE4:
                // memcpy( table_entry->reserve4,
                        // table_entry->old_reserve4,
                        // sizeof(table_entry->reserve4));
                // memset( table_entry->old_reserve4, 0,
                        // sizeof(table_entry->reserve4));
                // table_entry->reserve4_len =
                        // table_entry->old_reserve4_len;
                // break;
            // case COLUMN_RESERVE5:
                // memcpy( table_entry->reserve5,
                        // table_entry->old_reserve5,
                        // sizeof(table_entry->reserve5));
                // memset( table_entry->old_reserve5, 0,
                        // sizeof(table_entry->reserve5));
                // table_entry->reserve5_len =
                        // table_entry->old_reserve5_len;
                // break;
            // case COLUMN_RESERVE6:
                // memcpy( table_entry->reserve6,
                        // table_entry->old_reserve6,
                        // sizeof(table_entry->reserve6));
                // memset( table_entry->old_reserve6, 0,
                        // sizeof(table_entry->reserve6));
                // table_entry->reserve6_len =
                        // table_entry->old_reserve6_len;
                // break;
            // case COLUMN_RESERVE7:
                // memcpy( table_entry->reserve7,
                        // table_entry->old_reserve7,
                        // sizeof(table_entry->reserve7));
                // memset( table_entry->old_reserve7, 0,
                        // sizeof(table_entry->reserve7));
                // table_entry->reserve7_len =
                        // table_entry->old_reserve7_len;
                // break;
            // case COLUMN_RESERVE8:
                // memcpy( table_entry->reserve8,
                        // table_entry->old_reserve8,
                        // sizeof(table_entry->reserve8));
                // memset( table_entry->old_reserve8, 0,
                        // sizeof(table_entry->reserve8));
                // table_entry->reserve8_len =
                        // table_entry->old_reserve8_len;
                // break;
            // case COLUMN_SATEAPPLY:
                // table_entry->sateapply     = table_entry->old_sateapply;
                // table_entry->old_sateapply = 0;
                // break;
            // }
        // }
        break;

    case MODE_SET_COMMIT:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct sateTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATEROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_ACTIVE:
                    // table_entry->saterowstatus = RS_ACTIVE;
                    // break;

                // case RS_CREATEANDWAIT:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_NOTINSERVICE:
                    // table_entry->saterowstatus = RS_NOTINSERVICE;
                    // break;

                // case RS_DESTROY:
                    // sateTable_removeEntry(table_data, table_row );
                // }
            // }
        // }
        break;
    }
    return SNMP_ERR_NOERROR;
}
