/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "satethTable.h"
#include "LoopApp.h"
#define STRLEN 32

int static_applyth[MAX_CHANNEL_NUM] = {0};

struct satethTable_entry *
satethTable_createEntry(
                 long  indexth
                ) ;
/** Initializes the satethTable module */
void
init_satethTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_satethTable();
}



/** Initialize the satethTable table by defining its contents and how it's structured */
void
initialize_table_satethTable(void)
{
    const oid satethTable_oid[] = {1,3,6,1,4,1,71200,4};
    const size_t satethTable_oid_len   = OID_LENGTH(satethTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("satethTable:init", "initializing table satethTable\n"));

    reg = netsnmp_create_handler_registration(
              "satethTable",     satethTable_handler,
              satethTable_oid, satethTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: indexth */
                           0);
    table_info->min_column = COLUMN_SATETHROWSTATUS;
    table_info->max_column = COLUMN_SATETHAPPLY;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = satethTable_get_first_data_point;
    iinfo->get_next_data_point  = satethTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    int i = 0;
    for(i=0;i<MAX_CHANNEL_NUM;i++)    satethTable_createEntry(i);
}

    /* Typical data structure for a row entry */
struct satethTable_entry {
    /* Index values */
    long indexth;

    /* Column values */
    long satethrowstatus;
    long rxpwrlow;
    long rxpwrhigh;
    long snrlow;
    long merlow;
    long evmlow;
    long freqoffsetmax;
    long symoffsetmax;
    long bermax;
    long feclockSW;
    long agclockSW;
    long satethapply;

    /* Illustrate using a simple linked list */
    int   valid;
    struct satethTable_entry *next;
};

struct satethTable_entry  *satethTable_head;

/* create a new row in the (unsorted) table */
struct satethTable_entry *
satethTable_createEntry(
                 long  indexth
                ) {
    struct satethTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct satethTable_entry);
    if (!entry)
        return NULL;

    entry->indexth = indexth;
    entry->next = satethTable_head;
    satethTable_head = entry;

    return entry;
}

/* remove a row from the table */
void
satethTable_removeEntry( struct satethTable_entry *entry ) {
    struct satethTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = satethTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        satethTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
satethTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = satethTable_head;
    return satethTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
satethTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct satethTable_entry *entry = (struct satethTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->indexth );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the satethTable table */
int
satethTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct satethTable_entry          *table_entry;

    DEBUGMSGTL(("satethTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct satethTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SATETHROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->satethrowstatus);
                break;
            case COLUMN_RXPWRLOW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->rxpwrlow = dev->sd_thPtr[table_entry->indexth]->rxpwrLow;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rxpwrlow);
                break;
            case COLUMN_RXPWRHIGH:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->rxpwrhigh = dev->sd_thPtr[table_entry->indexth]->rxpwrHigh;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->rxpwrhigh);
                break;
            case COLUMN_SNRLOW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->snrlow = dev->sd_thPtr[table_entry->indexth]->snrLow;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->snrlow);
                break;
            case COLUMN_MERLOW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->merlow = dev->sd_thPtr[table_entry->indexth]->merLow;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->merlow);
                break;
            case COLUMN_EVMLOW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->evmlow = dev->sd_thPtr[table_entry->indexth]->evmLow;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->evmlow);
                break;
            case COLUMN_FREQOFFSETMAX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->freqoffsetmax = dev->sd_thPtr[table_entry->indexth]->cfoMax_Hz;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->freqoffsetmax);
                break;
            case COLUMN_SYMOFFSETMAX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->symoffsetmax = dev->sd_thPtr[table_entry->indexth]->sfo_symbol;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->symoffsetmax);
                break;
            case COLUMN_BERMAX:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->bermax = dev->sd_thPtr[table_entry->indexth]->berMax;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->bermax);
                break;
            case COLUMN_FECLOCKSW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->feclockSW = dev->sd_thPtr[table_entry->indexth]->lockSwitch;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->feclockSW);
                break;
            case COLUMN_AGCLOCKSW:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->agclockSW = 0;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->agclockSW);
                break;
            case COLUMN_SATETHAPPLY:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->satethapply = static_applyth[table_entry->indexth];
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->satethapply);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct satethTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATETHROWSTATUS:
                // ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         // (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RXPWRLOW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_RXPWRHIGH:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_SNRLOW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_MERLOW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_EVMLOW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_FREQOFFSETMAX:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_SYMOFFSETMAX:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_BERMAX:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->bermax));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_FECLOCKSW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_AGCLOCKSW:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                break;
            // case COLUMN_SATETHAPPLY:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // default:
                // netsnmp_set_request_error( reqinfo, request,
                                           // SNMP_ERR_NOTWRITABLE );
                // return SNMP_ERR_NOERROR;
            // }
        // }
        break;

    case MODE_SET_RESERVE2:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct satethTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATETHROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // table_row = satethTable_createEntry(
                        // , *table_info->indexes->val.integer
                        // );
                    // if (table_row) {
                        // netsnmp_insert_iterator_context( request, table_row );
                    // } else {
                        // netsnmp_set_request_error( reqinfo, request,
                                                   // SNMP_ERR_RESOURCEUNAVAILABLE );
                        // return SNMP_ERR_NOERROR;
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_FREE:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct satethTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATETHROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // satethTable_removeEntry(table_data, table_row );
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct satethTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_RXPWRLOW:
                table_entry->rxpwrlow     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->rxpwrLow = table_entry->rxpwrlow;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_RXPWRHIGH:
                table_entry->rxpwrhigh     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->rxpwrHigh = table_entry->rxpwrhigh;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_SNRLOW:
                table_entry->snrlow     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->snrLow = table_entry->snrlow;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_MERLOW:
                table_entry->merlow     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->merLow = table_entry->merlow;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_EVMLOW:
                table_entry->evmlow     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->evmLow = table_entry->evmlow;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_FREQOFFSETMAX:
                table_entry->freqoffsetmax     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->cfoMax_Hz = table_entry->freqoffsetmax;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_SYMOFFSETMAX:
                table_entry->symoffsetmax     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->sfo_symbol = table_entry->symoffsetmax;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_BERMAX:
                table_entry->bermax     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->berMax = table_entry->bermax;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_FECLOCKSW:
                table_entry->feclockSW     = *request->requestvb->val.integer;
                dev->sd_thPtr[table_entry->indexth]->lockSwitch = table_entry->feclockSW;
                static_applyth[table_entry->indexth] = 1;
                break;
            case COLUMN_AGCLOCKSW:
                table_entry->agclockSW     = *request->requestvb->val.integer;
                break;
            case COLUMN_SATETHAPPLY:
                table_entry->satethapply     = *request->requestvb->val.integer;
                if(static_applyth[table_entry->indexth]){
                    puts("TODO: confile_th_update");
                    static_applyth[table_entry->indexth] = 0;
                }
                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct satethTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_SATETHROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (/* XXX */0) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct satethTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATETHROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // satethTable_removeEntry(table_data, table_row );
                    // }
                // }
                // break;
            // case COLUMN_RXPWRLOW:
                // table_entry->rxpwrlow     = table_entry->old_rxpwrlow;
                // table_entry->old_rxpwrlow = 0;
                // break;
            // case COLUMN_RXPWRHIGH:
                // table_entry->rxpwrhigh     = table_entry->old_rxpwrhigh;
                // table_entry->old_rxpwrhigh = 0;
                // break;
            // case COLUMN_SNRLOW:
                // table_entry->snrlow     = table_entry->old_snrlow;
                // table_entry->old_snrlow = 0;
                // break;
            // case COLUMN_MERLOW:
                // table_entry->merlow     = table_entry->old_merlow;
                // table_entry->old_merlow = 0;
                // break;
            // case COLUMN_EVMLOW:
                // table_entry->evmlow     = table_entry->old_evmlow;
                // table_entry->old_evmlow = 0;
                // break;
            // case COLUMN_FREQOFFSETMAX:
                // table_entry->freqoffsetmax     = table_entry->old_freqoffsetmax;
                // table_entry->old_freqoffsetmax = 0;
                // break;
            // case COLUMN_SYMOFFSETMAX:
                // table_entry->symoffsetmax     = table_entry->old_symoffsetmax;
                // table_entry->old_symoffsetmax = 0;
                // break;
            // case COLUMN_BERMAX:
                // memcpy( table_entry->bermax,
                        // table_entry->old_bermax,
                        // sizeof(table_entry->bermax));
                // memset( table_entry->old_bermax, 0,
                        // sizeof(table_entry->bermax));
                // table_entry->bermax_len =
                        // table_entry->old_bermax_len;
                // break;
            // case COLUMN_FECLOCKSW:
                // table_entry->feclockSW     = table_entry->old_feclockSW;
                // table_entry->old_feclockSW = 0;
                // break;
            // case COLUMN_AGCLOCKSW:
                // table_entry->agclockSW     = table_entry->old_agclockSW;
                // table_entry->old_agclockSW = 0;
                // break;
            // case COLUMN_SATETHAPPLY:
                // table_entry->satethapply     = table_entry->old_satethapply;
                // table_entry->old_satethapply = 0;
                // break;
            // }
        // }
        break;

    case MODE_SET_COMMIT:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct satethTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_SATETHROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_ACTIVE:
                    // table_entry->satethrowstatus = RS_ACTIVE;
                    // break;

                // case RS_CREATEANDWAIT:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_NOTINSERVICE:
                    // table_entry->satethrowstatus = RS_NOTINSERVICE;
                    // break;

                // case RS_DESTROY:
                    // satethTable_removeEntry(table_data, table_row );
                // }
            // }
        // }
        break;
    }
    return SNMP_ERR_NOERROR;
}
