/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SATETABLE_H
#define SATETABLE_H

/* function declarations */
void init_sateTable(void);
void initialize_table_sateTable(void);
Netsnmp_Node_Handler sateTable_handler;
Netsnmp_First_Data_Point  sateTable_get_first_data_point;
Netsnmp_Next_Data_Point   sateTable_get_next_data_point;

/* column number definitions for table sateTable */
       #define COLUMN_SATEROWSTATUS		1
       #define COLUMN_INPUTPORT		2
       #define COLUMN_MODE		3
       #define COLUMN_FREQUENCY		4
       #define COLUMN_MODULATION		5
       #define COLUMN_SYMBOLRATE		6
       #define COLUMN_FEC		7
       #define COLUMN_SPECTRUM		8
       #define COLUMN_ROLLOFF		9
       #define COLUMN_PILOT		10
       #define COLUMN_FREQSEARCHRANGE		11
       #define COLUMN_RESERVE1		12
       #define COLUMN_RESERVE2		13
       #define COLUMN_RESERVE3		14
       #define COLUMN_RESERVE4		15
       #define COLUMN_RESERVE5		16
       #define COLUMN_RESERVE6		17
       #define COLUMN_RESERVE7		18
       #define COLUMN_RESERVE8		19
       #define COLUMN_RXPWR		20
       #define COLUMN_SNR		21
       #define COLUMN_MER		22
       #define COLUMN_EVM		23
       #define COLUMN_EBN0		24
       #define COLUMN_FREQOFFSET		25
       #define COLUMN_SYMOFFSET		26
       #define COLUMN_AGCLOCK		27
       #define COLUMN_FECLOCK		28
       #define COLUMN_CORRRSERRORSSDSS		29
       #define COLUMN_RSERRORSSDSS		30
       #define COLUMN_BERWINDOWSDSS		31
       #define COLUMN_BERCOUNTSDSS		32
       #define COLUMN_CORRRSERRORS1SDSS		33
       #define COLUMN_RSERRORS1SDSS		34
       #define COLUMN_BERWINDOWITER1SDSS		35
       #define COLUMN_BERCOUNTITER1SDSS		36
       #define COLUMN_CRCERRORSS2		37
       #define COLUMN_PACKETERRORCOUNTS2		38
       #define COLUMN_TOTALPACKETSS2		39
       #define COLUMN_BER		40
       #define COLUMN_RESERVE11		41
       #define COLUMN_RESERVE12		42
       #define COLUMN_RESERVE13		43
       #define COLUMN_INDEX		99
       #define COLUMN_SATEAPPLY		100
#endif /* SATETABLE_H */
