/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef SATETHTABLE_H
#define SATETHTABLE_H

/* function declarations */
void init_satethTable(void);
void initialize_table_satethTable(void);
Netsnmp_Node_Handler satethTable_handler;
Netsnmp_First_Data_Point  satethTable_get_first_data_point;
Netsnmp_Next_Data_Point   satethTable_get_next_data_point;

/* column number definitions for table satethTable */
       #define COLUMN_INDEXTH		1
       #define COLUMN_SATETHROWSTATUS		2
       #define COLUMN_RXPWRLOW		3
       #define COLUMN_RXPWRHIGH		4
       #define COLUMN_SNRLOW		5
       #define COLUMN_MERLOW		6
       #define COLUMN_EVMLOW		7
       #define COLUMN_FREQOFFSETMAX		8
       #define COLUMN_SYMOFFSETMAX		9
       #define COLUMN_BERMAX		10
       #define COLUMN_FECLOCKSW		11
       #define COLUMN_AGCLOCKSW		12
       #define COLUMN_SATETHAPPLY		13
#endif /* SATETHTABLE_H */
