/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "sysdescr.h"
#include <string.h>
/** Initializes the sysdescr module */
void
init_sysdescr(void)
{
    const oid descrption_oid[] = { 1,3,6,1,4,1,71200,99,1 };
    const oid sysid_oid[] = { 1,3,6,1,4,1,71200,99,2 };
    const oid sysdescrapply_oid[] = { 1,3,6,1,4,1,71200,99,3 };

  DEBUGMSGTL(("sysdescr", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("descrption", handle_descrption,
                               descrption_oid, OID_LENGTH(descrption_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysid", handle_sysid,
                               sysid_oid, OID_LENGTH(sysid_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sysdescrapply", handle_sysdescrapply,
                               sysdescrapply_oid, OID_LENGTH(sysdescrapply_oid),
                               HANDLER_CAN_RWRITE
        ));
}

int
handle_descrption(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    char* s = "Designer is yhmcjc@sina.com";
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR,
                                     /* XXX: a pointer to the scalar's data */s,
                                     /* XXX: the length of the data in bytes */strlen(s));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            // ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            // if ( ret != SNMP_ERR_NOERROR ) {
                // netsnmp_set_request_error(reqinfo, requests, ret );
            // }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            // if (/* XXX if malloc, or whatever, failed: */) {
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            // }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            strcpy(s, (char*)requests->requestvb->val.string);
            if (/* XXX: error? */0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED/* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            // }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            // }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_descrption\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_sysid(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    int id = 1024;
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     /* XXX: a pointer to the scalar's data */&id,
                                     /* XXX: the length of the data in bytes */sizeof(id));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            // ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            // if ( ret != SNMP_ERR_NOERROR ) {
                // netsnmp_set_request_error(reqinfo, requests, ret );
            // }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            // if (/* XXX if malloc, or whatever, failed: */) {
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            // }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            if (/* XXX: error? */0) {
                netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED/* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            // }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            // }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysid\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
int
handle_sysdescrapply(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret = 0;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    
    switch(reqinfo->mode) {

        case MODE_GET:
            snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     /* XXX: a pointer to the scalar's data */&ret,
                                     /* XXX: the length of the data in bytes */sizeof(ret));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            // ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            // if ( ret != SNMP_ERR_NOERROR ) {
                // netsnmp_set_request_error(reqinfo, requests, ret );
            // }
            break;

        case MODE_SET_RESERVE2:
            /* XXX malloc "undo" storage buffer */
            // if (/* XXX if malloc, or whatever, failed: */) {
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_RESOURCEUNAVAILABLE);
            // }
            break;

        case MODE_SET_FREE:
            /* XXX: free resources allocated in RESERVE1 and/or
               RESERVE2.  Something failed somewhere, and the states
               below won't be called. */
            break;

        case MODE_SET_ACTION:
            /* XXX: perform the value change here */
            if (/* XXX: error? */0) {
                netsnmp_set_request_error(reqinfo, requests,SNMP_ERR_COMMITFAILED /* some error */);
            }
            break;

        case MODE_SET_COMMIT:
            /* XXX: delete temporary storage */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_COMMITFAILED);
            // }
            break;

        case MODE_SET_UNDO:
            /* XXX: UNDO and return to previous value for the object */
            // if (/* XXX: error? */) {
                // /* try _really_really_ hard to never get to this point */
                // netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            // }
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_sysdescrapply\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
