/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef SYSDESCR_H
#define SYSDESCR_H

/* function declarations */
void init_sysdescr(void);
Netsnmp_Node_Handler handle_descrption;
Netsnmp_Node_Handler handle_sysid;
Netsnmp_Node_Handler handle_sysdescrapply;

#endif /* SYSDESCR_H */
