/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef TRAP_H
#define TRAP_H

/* function declarations */
int send_reset_trap(char* s);
int send_start_trap(char* s);
int send_rxpwrtrap_trap(int i, char* s);
int send_snrtrap_trap(int i, char* s);
int send_mertrap_trap(int i, char* s);
int send_evmtrap_trap(int i, char* s);
int send_freqoffsettrap_trap(int i, char* s);
int send_symoffsettrap_trap(int i, char* s);
int send_agclocktrap_trap(void);
int send_feclocktrap_trap(int i, char* s);

#endif /* TRAP_H */
