/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef UDPTABLE_H
#define UDPTABLE_H

/* function declarations */
void init_udpTable(void);
void initialize_table_udpTable(void);
Netsnmp_Node_Handler udpTable_handler;
Netsnmp_First_Data_Point  udpTable_get_first_data_point;
Netsnmp_Next_Data_Point   udpTable_get_next_data_point;

/* column number definitions for table udpTable */
       #define COLUMN_UDPINDEX		1
       #define COLUMN_UDPROWSTATUS		2
       #define COLUMN_IP		3
       #define COLUMN_PORT		4
#endif /* UDPTABLE_H */
