/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "udpTable.h"
#include "LoopApp.h"
#include <string.h>

struct udpTable_entry *
udpTable_createEntry(
                 long  udpindex
                );
/** Initializes the udpTable module */
void
init_udpTable(void)
{
  /* here we initialize all the tables we're planning on supporting */
    initialize_table_udpTable();
}



/** Initialize the udpTable table by defining its contents and how it's structured */
void
initialize_table_udpTable(void)
{
    const oid udpTable_oid[] = {1,3,6,1,4,1,71200,6};
    const size_t udpTable_oid_len   = OID_LENGTH(udpTable_oid);
    netsnmp_handler_registration    *reg;
    netsnmp_iterator_info           *iinfo;
    netsnmp_table_registration_info *table_info;

    DEBUGMSGTL(("udpTable:init", "initializing table udpTable\n"));

    reg = netsnmp_create_handler_registration(
              "udpTable",     udpTable_handler,
              udpTable_oid, udpTable_oid_len,
              HANDLER_CAN_RWRITE
              );

    table_info = SNMP_MALLOC_TYPEDEF( netsnmp_table_registration_info );
    netsnmp_table_helper_add_indexes(table_info,
                           ASN_INTEGER,  /* index: udpindex */
                           0);
    table_info->min_column = COLUMN_UDPROWSTATUS;
    table_info->max_column = COLUMN_PORT;
    
    iinfo = SNMP_MALLOC_TYPEDEF( netsnmp_iterator_info );
    iinfo->get_first_data_point = udpTable_get_first_data_point;
    iinfo->get_next_data_point  = udpTable_get_next_data_point;
    iinfo->table_reginfo        = table_info;
    
    netsnmp_register_table_iterator( reg, iinfo );

    /* Initialise the contents of the table here */
    int i = 0;
    for(i=0;i<MAX_UDP_ADDR;i++)     udpTable_createEntry(i);
}

    /* Typical data structure for a row entry */
struct udpTable_entry {
    /* Index values */
    long udpindex;

    /* Column values */
    long udprowstatus;
    char ip[16];
    size_t ip_len;
    long port;

    /* Illustrate using a simple linked list */
    int   valid;
    struct udpTable_entry *next;
};

struct udpTable_entry  *udpTable_head;

/* create a new row in the (unsorted) table */
struct udpTable_entry *
udpTable_createEntry(
                 long  udpindex
                ) {
    struct udpTable_entry *entry;

    entry = SNMP_MALLOC_TYPEDEF(struct udpTable_entry);
    if (!entry)
        return NULL;
    memset(entry,0,sizeof(struct udpTable_entry));
    entry->udpindex = udpindex;
    entry->next = udpTable_head;
    udpTable_head = entry;
    entry->ip_len = 16;
    return entry;
}

/* remove a row from the table */
void
udpTable_removeEntry( struct udpTable_entry *entry ) {
    struct udpTable_entry *ptr, *prev;

    if (!entry)
        return;    /* Nothing to remove */

    for ( ptr  = udpTable_head, prev = NULL;
          ptr != NULL;
          prev = ptr, ptr = ptr->next ) {
        if ( ptr == entry )
            break;
    }
    if ( !ptr )
        return;    /* Can't find it */

    if ( prev == NULL )
        udpTable_head = ptr->next;
    else
        prev->next = ptr->next;

    SNMP_FREE( entry );   /* XXX - release any other internal resources */
}


/* Example iterator hook routines - using 'get_next' to do most of the work */
netsnmp_variable_list *
udpTable_get_first_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    *my_loop_context = udpTable_head;
    return udpTable_get_next_data_point(my_loop_context, my_data_context,
                                    put_index_data,  mydata );
}

netsnmp_variable_list *
udpTable_get_next_data_point(void **my_loop_context,
                          void **my_data_context,
                          netsnmp_variable_list *put_index_data,
                          netsnmp_iterator_info *mydata)
{
    struct udpTable_entry *entry = (struct udpTable_entry *)*my_loop_context;
    netsnmp_variable_list *idx = put_index_data;

    if ( entry ) {
        snmp_set_var_typed_integer( idx, ASN_INTEGER, entry->udpindex );
        idx = idx->next_variable;
        *my_data_context = (void *)entry;
        *my_loop_context = (void *)entry->next;
        return put_index_data;
    } else {
        return NULL;
    }
}


/** handles requests for the udpTable table */
int
udpTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {

    netsnmp_request_info       *request;
    netsnmp_table_request_info *table_info;
    struct udpTable_entry          *table_entry;

    DEBUGMSGTL(("udpTable:handler", "Processing request (%d)\n", reqinfo->mode));

    switch (reqinfo->mode) {
        /*
         * Read-support (also covers GetNext requests)
         */
    case MODE_GET:
        for (request=requests; request; request=request->next) {
            table_entry = (struct udpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_UDPROWSTATUS:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->udprowstatus);
                break;
            case COLUMN_IP:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                strcpy(table_entry->ip,udp_ipPtr[table_entry->udpindex].ip);
                snmp_set_var_typed_value( request->requestvb, ASN_OCTET_STR,
                                          table_entry->ip,
                                          table_entry->ip_len);
                break;
            case COLUMN_PORT:
                if ( !table_entry ) {
                    netsnmp_set_request_error(reqinfo, request,
                                              SNMP_NOSUCHINSTANCE);
                    continue;
                }
                table_entry->port = udp_ipPtr[table_entry->udpindex].port;
                snmp_set_var_typed_integer( request->requestvb, ASN_INTEGER,
                                            table_entry->port);
                break;
            default:
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHOBJECT);
                break;
            }
        }
        break;

        /*
         * Write-support
         */
    case MODE_SET_RESERVE1:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct udpTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_UDPROWSTATUS:
                // ret = netsnmp_check_vb_rowstatus(request->requestvb,
                         // (table_entry ? RS_ACTIVE : RS_NONEXISTENT ));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_IP:
            // /* or possibly 'netsnmp_check_vb_type_and_size' */
                // ret = netsnmp_check_vb_type_and_max_size(
                          // request->requestvb, ASN_OCTET_STR, sizeof(table_entry->ip));
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // case COLUMN_PORT:
                // /* or possibly 'netsnmp_check_vb_int_range' */
                // ret = netsnmp_check_vb_int( request->requestvb );
                // if ( ret != SNMP_ERR_NOERROR ) {
                    // netsnmp_set_request_error( reqinfo, request, ret );
                    // return SNMP_ERR_NOERROR;
                // }
                // break;
            // default:
                // netsnmp_set_request_error( reqinfo, request,
                                           // SNMP_ERR_NOTWRITABLE );
                // return SNMP_ERR_NOERROR;
            // }
        // }
        break;

    case MODE_SET_RESERVE2:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct udpTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_UDPROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // table_row = udpTable_createEntry(
                        // , *table_info->indexes->val.integer
                        // );
                    // if (table_row) {
                        // netsnmp_insert_iterator_context( request, table_row );
                    // } else {
                        // netsnmp_set_request_error( reqinfo, request,
                                                   // SNMP_ERR_RESOURCEUNAVAILABLE );
                        // return SNMP_ERR_NOERROR;
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_FREE:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct udpTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_UDPROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // udpTable_removeEntry(table_data, table_row );
                    // }
                // }
            // }
        // }
        break;

    case MODE_SET_ACTION:
        for (request=requests; request; request=request->next) {
            table_entry = (struct udpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_IP:
                memset( table_entry->ip, 0,
                        sizeof(table_entry->ip));
                memcpy( table_entry->ip,
                        request->requestvb->val.string,
                        request->requestvb->val_len);
                table_entry->ip_len =
                        request->requestvb->val_len;
                strcpy(udp_ipPtr[table_entry->udpindex].ip, table_entry->ip);
                udpTarget_IPupdate(table_entry->udpindex,udp_ipPtr);
                break;
            case COLUMN_PORT:
                table_entry->port     = *request->requestvb->val.integer;
                udp_ipPtr[table_entry->udpindex].port = table_entry->port;
                udpTarget_IPupdate(table_entry->udpindex,udp_ipPtr);
                break;
            }
        }
        /* Check the internal consistency of an active row */
        for (request=requests; request; request=request->next) {
            table_entry = (struct udpTable_entry *)
                              netsnmp_extract_iterator_context(request);
            table_info  =     netsnmp_extract_table_info(      request);
    
            switch (table_info->colnum) {
            case COLUMN_UDPROWSTATUS:
                switch (*request->requestvb->val.integer) {
                case RS_ACTIVE:
                case RS_CREATEANDGO:
                    if (/* XXX */0) {
                        netsnmp_set_request_error( reqinfo, request,
                                                   SNMP_ERR_INCONSISTENTVALUE );
                        return SNMP_ERR_NOERROR;
                    }
                }
            }
        }
        break;

    case MODE_SET_UNDO:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct udpTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_UDPROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                // case RS_CREATEANDWAIT:
                    // if (table_entry && !table_entry->valid) {
                        // udpTable_removeEntry(table_data, table_row );
                    // }
                // }
                // break;
            // case COLUMN_IP:
                // memcpy( table_entry->ip,
                        // table_entry->old_ip,
                        // sizeof(table_entry->ip));
                // memset( table_entry->old_ip, 0,
                        // sizeof(table_entry->ip));
                // table_entry->ip_len =
                        // table_entry->old_ip_len;
                // break;
            // case COLUMN_PORT:
                // table_entry->port     = table_entry->old_port;
                // table_entry->old_port = 0;
                // break;
            // }
        // }
        break;

    case MODE_SET_COMMIT:
        // for (request=requests; request; request=request->next) {
            // table_entry = (struct udpTable_entry *)
                              // netsnmp_extract_iterator_context(request);
            // table_info  =     netsnmp_extract_table_info(      request);
    
            // switch (table_info->colnum) {
            // case COLUMN_UDPROWSTATUS:
                // switch (*request->requestvb->val.integer) {
                // case RS_CREATEANDGO:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_ACTIVE:
                    // table_entry->udprowstatus = RS_ACTIVE;
                    // break;

                // case RS_CREATEANDWAIT:
                    // table_entry->valid = 1;
                    // /* Fall-through */
                // case RS_NOTINSERVICE:
                    // table_entry->udprowstatus = RS_NOTINSERVICE;
                    // break;

                // case RS_DESTROY:
                    // udpTable_removeEntry(table_data, table_row );
                // }
            // }
        // }
        break;
    }
    return SNMP_ERR_NOERROR;
}
